costCode: CDSO024
projectCode: DevSecOps
projectCode: aazzxxyy
infra:
  zone: a,b,c
  region: us-e
tags:
  machine: frontdrive
  rack: 4c
  drive: ssd
  vcard: 8g
LangUsed: 
  - Python
  - Java
  - Ruby
  - Scala
